### ISSUE TITLE
Known Issues & Bugs

### ISSUE THREAD

**Issue by OregSamSas** [OregSamSas/vardle#1]
- [x] &numero;1 whatever the last guess is, you lose following your submitting it
- [x] &numero;2 disappearing guesses (saves it to Guesses array, but does not display it)
- [x] &numero;3 Missing diacritic marks (Nograd, Bekes) + Túrócz: change spelling to "Turóc" according to, among others, Wikipedia. Also "Verőcze".
- [x] &numero;4 Gömör-és-kis-hont -> "Unknown territory"
- [x] &numero;5 inputs staying displayed after 6 guesses
- [x] &numero;6 ~~Lika-Krbava has a wrong wikipedia link (one linked to Modruš-Rijeka), but don't know why~~ The Wikipedia link was to the most lately guessed county, and not for the solution, this way, when failed, it always referred to the wrong article.
- [ ] &numero;7 On some devices, it was experienced, the grey frames of the elements had completely disappeared
- [x] &numero;8 [#comment3](https://github.com/OregSamSas/vardle/issues/1#issuecomment-1563458410) Update: it was a silly mistake during direction calculations: forget to handle the case of the last "half-(plain)-quadrant", which rounded up not 0 rather 8 which was out of the array
- [ ] &numero;9 In some browsers the "!important" CSS expression does not take any effect
- [x] &numero;10 Spelling of "Gömör-és-Kis-Hont" and "Jász-Nagy-Kun-Szolnok" should be rather "...-Kishont" and "...-Nagykun-..."
- [x] &numero;11 Missing confetti animations
- [x] &numero;12 #2
- [ ] &numero;13 Territory images of later rounds don't want to be hidden on setting "Hide county image for more of a challenge"
- [ ] &numero;14 Some problems again with direction calculation (see: [#comment4](https://github.com/OregSamSas/vardle/issues/1#issuecomment-1872251682))
- [x] &numero;15 Shaking animation of the last wrongly selected CoA image displays every single time, you visit the specific round
- [x] &numero;16 Not getting translation piece: https://github.com/OregSamSas/vardle/issues/2#issuecomment-1872257647
- [x] &numero;17 Styling is not yet perfect, especially meaning colours (dark map on light theme, too dark green-600 colour etc.)
- [ ] &numero;18 Zoomable map would be useful for mobile devices
- [x] &numero;19 Code should be documented properly
- [x] &numero;20 Strange NaN-s appearing at the path d attributes
- [ ] &numero;21 #3

**Comment by OregSamSas** [comment]
No1: it was a logical mistake: although it was a good guess, if it was the last one, the "lose" scenario was triggered.
No3: changed in SVG and also reworked on the key names of data.json.
No4: problems with titleCase() function: conjunctives shouldn't be capitalised (like "és" in "Gömör-és-Kis-Hont)

**Comment by OregSamSas** [comment]
This calculation is still not perfect.
![image](https://github.com/OregSamSas/vardle/assets/101597941/f8b321a5-3d8f-4279-8eb3-2f10a0f55160)
Although:
![image](https://github.com/OregSamSas/vardle/assets/101597941/11edf7f5-c120-4733-a354-043f26728800)

**Comment by OregSamSas** [comment]
Numero 7, 9, 13 and 14 should be tested further, especially in Chrome and Safari browsers. In Firefox, I haven't experienced them for a while now.

**Comment by OregSamSas** [comment]
&numero;20: 
![image](https://github.com/OregSamSas/vardle/assets/101597941/aed344a4-b92c-4b9e-9ddc-093785895ca4)
There's a problem with the AbsToRel() function.

**Comment by OregSamSas** [comment]
&numero;21: 
![image](https://github.com/OregSamSas/vardle/assets/101597941/c5844148-d96b-412f-af2d-8d57fa80a247)

**Comment by OregSamSas** [comment]
> This calculation is still not perfect. ![image](https://private-user-images.githubusercontent.com/101597941/293406076-f8b321a5-3d8f-4279-8eb3-2f10a0f55160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzQwMTIsIm5iZiI6MTcxOTA3MzcxMiwicGF0aCI6Ii8xMDE1OTc5NDEvMjkzNDA2MDc2LWY4YjMyMWE1LTNkOGYtNDI3OS04ZWIzLTJmMTBhMGY1NTE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNjI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDU0OWIzNmQyOWQ0NDRhMzBhNGRjMTE4NzFmMDYwNjgwMjA1MDg0YzliMTJmNzIzZmQ1MGEwYTVmMTc4MzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QN25VpBXut4rgG24rLwzDaIY0q8n6pbzoq3n9oKTDFs) Although: ![image](https://private-user-images.githubusercontent.com/101597941/293406164-11edf7f5-c120-4733-a354-043f26728800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzQwMTIsIm5iZiI6MTcxOTA3MzcxMiwicGF0aCI6Ii8xMDE1OTc5NDEvMjkzNDA2MTY0LTExZWRmN2Y1LWMxMjAtNDczMy1hMzU0LTA0M2YyNjcyODgwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNjI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjIyOTQ0MTUwMjlhMDRlZGE4NDkzZTBlNjg1NGQ4OTFjNGMyNzM3YjA3MDlmNjA3ZTE5YmE3MTI0MDQ0NzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1mje8M1BhZW5H3EOQ66UZNa5p2L67FocHKqHxwos-aw)

I can't reproduce this curious mistake, so I think, I'll mark it as resolved.
![image](https://github.com/OregSamSas/vardle/assets/101597941/52860872-4216-4927-9f6c-403f0b16fe36)

**Comment by OregSamSas** [comment]
&numero;24 
![image](https://github.com/user-attachments/assets/f7d0efce-8534-4419-8f59-35d59c5ddcae)

**Comment by OregSamSas** [comment]
> &numero;24 
> ![image](https://github.com/user-attachments/assets/f7d0efce-8534-4419-8f59-35d59c5ddcae)

It was a problem with the function `insertSpacesToNum()` which returned with the value `NaN` when was given the input `0`.
