### ISSUE TITLE
Include cities of the Kingdom in the game

### ISSUE THREAD

**Issue by OregSamSas** [OregSamSas/vardle#6]
## Idea 
add further rounds for guessing the capital cities of the county and its location

## To-do

- modify the SVG image, so that it has the data needed
- [x] create circles under a group called "settlements" for cities, with their position data
- [x] sign which city is a capital of a county, and which county then
- acquire this data from the SVG
- [x] determine which county does the city belong to
- [x] collect position data into a global object
- make the first new round, where the player have to guess the capital of the county from all of the city names
- [x] update suggestions to show cites instead of counties
- [x] accept cities as guesses and not counties
- [x] make guesslines suitable (similar to round No2)
- [x] sign if the guessed city is in the same county but not the capital
- [x] modify updating rounds
- [x] place a question for round
- [x] fix bug with question duplicating when gave up
- [x] if not guessed, write the correct solution
- [x] update wikipedia link for round
- [x] add new placeholder for input
- make the 2nd new round, where the player have to guess the position of the capital
- [ ] create an environment for it
- [ ] place a question for round
- and perhaps  3rd round for naming other counties from the county if there are (?)
- update the helping map accordingly to the new feature
- [x] make that only on the cities rounds should the cities be displayed on the map
- [x] add a button to the top left corner of the map to toggle cities on map
- [x] on hovering a city position, a small label should come up with the name of the city
- [ ] rework the label to look more advanced and stylish
- fix issues
- [ ] hiding and rotating of the county image should be disabled in 5th round, since the county image is only there in order to have some image on the screen (hiding it doesn't really make harder the guessing of the capital, since the player has already seen the shape of the territory and nonetheless, it isn't the question)

## Images

How the new round looks like ([live here](https://oregsamsas.github.io/vardle/?sol=zala&round=4)):
<img width="60%" src=https://github.com/user-attachments/assets/23d25421-6f2c-4401-9b9c-c45d92a58257></img>
How the map looks like:
<img width="60%" src="https://github.com/user-attachments/assets/9ff64f86-f061-44b4-9cf2-4d4833fb1a67"></img>

**Comment by OregSamSas** [comment]
Note No1: Capital of Csongrád is Szentes at that time and not Szeged.
